use_frameworks!

platform :ios, '16.0'

target 'Build-V3-Plugin-Optimizers-ios-Example' do
  pod 'Build-V3-Plugin-Optimizers-ios', :path => '../'
  pod 'FASDKBuild-ios', '3.9.8-beta.1828', :source => 'git@github.com:bryjai/bryj-build-private-pods.git'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
  end
end
