use_frameworks!

platform :ios, '15.0'

target 'FASDKBuild-Plugin-Optimizers-ios_Example' do
  pod 'Build-V3-Plugin-Optimizers-ios', :path => '../'
  pod 'FASDKBuild-ios', '3.9.5', :source => 'git@github.com:bryjai/bryj-build-private-pods.git'

  target 'FASDKBuild-Plugin-Optimizers-ios_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
  end
end
